security:
    encoders:
        App\Entity\User:
            algorithm: auto
        App\Entity\ApiUser:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\ApiUser
                property: username
        api_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^\/api
            lazy: true
            provider: api_user_provider
            guard:
                authenticators:
                    - App\Service\Security\ExternalApiLoginAuthenticator
        main:
            lazy: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Service\Security\VueApiLoginAuthenticator

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }                           # login page
         - { path: ^/system/get-csrf-token, roles: IS_AUTHENTICATED_ANONYMOUSLY }           # required as the login form needs csrf token as well
         - { path: ^/user/get-logged-in-user-data, roles: IS_AUTHENTICATED_ANONYMOUSLY }    # required as the login form needs that call
         - { path: ^/module/is-module-data-available, roles: IS_AUTHENTICATED_ANONYMOUSLY } # check if data is available in system - this happens before log-in process
         - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }                                   # API calls
         - { path: ^/.*, roles: ROLE_ADMIN }                                                # any other pages
