monolog:
    handlers:
        main:
            type: stream
            path: php://stderr
            level: debug
            channels: ["!event"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
