# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration

# https://github.com/mogilvie/EncryptBundle
parameters:
    encrypt_key: "0000000000000000000000000000000000000000000" # (random key - not used - needs to be set to suppress the encryption bundle error)
    path_to_encryption_file_with_key: "%kernel.project_dir%/data/encryption_key"

# https://ipinfo.io/developers/responses#free-plan
    ipinfo.access_token: 'Register on the page and add token here'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Action\:
        resource: '../src/Action/'
        tags: ['controller.service_arguments']

    App\Controller\Core\Services:
        public: true
        calls:
            - setAttributeReaderService: ['@App\Service\Attribute\AttributeReaderService']
            - setUrlMatcherService: ['@App\Service\Routing\UrlMatcherService']
            - setFormService: ['@App\Service\Form\FormService']
            - setLoggerService: ['@App\Service\Logger\LoggerService']
            - setTranslator: ['@translator']
            - setValidationService: ['@App\Service\Validation\ValidationService']
            - setDatabaseService: ['@App\Service\Database\DatabaseService']
            - setEncryptionService: ['@App\Service\Security\EncryptionService']
            - setUserSecurityService: ['@App\Service\Security\UserSecurityService']
            - setCsrfTokenValidatorService: ['@App\Service\Security\CsrfTokenValidatorService']
            - setFilesService: ['@App\Service\Files\FilesService']
            - setCookiesService: ['@App\Service\CookiesService']
            - setIpInfoService: ['@App\Service\External\IpInfoService']

    App\Service\ConfigLoader\ConfigLoaderPaths:
        public: true
        calls:
            - setTranslationBackendFolder: ['%paths.translations.backendFolder%']
            - setTranslationFrontendOutputFilePath: ['%paths.translations.frontendOutputFilePath%']
            - setRoutingFrontendFilePath: ['%paths.routing.frontendFilePath%']
            - setEncryptionFilePath: ["%path_to_encryption_file_with_key%"]

    App\Service\ConfigLoader\ConfigLoaderSystemData:
        public: true
        calls:
            - setMaxInactivityTime: ["%max_inactivity_time%"]

    App\Service\ConfigLoader\ConfigLoaderApi:
        public: true
        calls:
            - setIpInfoAccessToken: ["%ipinfo.access_token%"]

    App\Controller\Core\ConfigLoader:
        public: true
        calls:
            - setConfigLoaderPaths: ['@App\Service\ConfigLoader\ConfigLoaderPaths']
            - setConfigLoaderSystemData : ['@App\Service\ConfigLoader\ConfigLoaderSystemData']
            - setConfigLoaderApi : ['@App\Service\ConfigLoader\ConfigLoaderApi']

    App\Service\Security\EncryptionService:
        public: true
        calls:
            - initialize: ['@App\Service\Security\EncryptionService']

    ipinfo\ipinfo\IPinfo:
        public: true
        arguments:
            $access_token: "%ipinfo.access_token%"

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
